// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeFgXUtusXxN4l8IihtC7nFyPqrQSUlXo',
    appId: '1:812223087615:web:83af6aa00e9039fd635dca',
    messagingSenderId: '812223087615',
    projectId: 'fruit-and-car',
    authDomain: 'fruit-and-car.firebaseapp.com',
    databaseURL: 'https://fruit-and-car-default-rtdb.firebaseio.com',
    storageBucket: 'fruit-and-car.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVdyk0QPP32FKT4dUDo_8Yv18YwM-fBRI',
    appId: '1:812223087615:android:f62c5a8a45cdd3f7635dca',
    messagingSenderId: '812223087615',
    projectId: 'fruit-and-car',
    databaseURL: 'https://fruit-and-car-default-rtdb.firebaseio.com',
    storageBucket: 'fruit-and-car.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoZ3nYX-QZPRwNCVgWu1OugwzteOE89GY',
    appId: '1:812223087615:ios:bdd2fcf40c6c55e2635dca',
    messagingSenderId: '812223087615',
    projectId: 'fruit-and-car',
    databaseURL: 'https://fruit-and-car-default-rtdb.firebaseio.com',
    storageBucket: 'fruit-and-car.appspot.com',
    iosClientId: '812223087615-u51pqit56uem6f3dmhvq3urn3bm91po1.apps.googleusercontent.com',
    iosBundleId: 'com.example.admin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoZ3nYX-QZPRwNCVgWu1OugwzteOE89GY',
    appId: '1:812223087615:ios:bdd2fcf40c6c55e2635dca',
    messagingSenderId: '812223087615',
    projectId: 'fruit-and-car',
    databaseURL: 'https://fruit-and-car-default-rtdb.firebaseio.com',
    storageBucket: 'fruit-and-car.appspot.com',
    iosClientId: '812223087615-u51pqit56uem6f3dmhvq3urn3bm91po1.apps.googleusercontent.com',
    iosBundleId: 'com.example.admin',
  );
}
